---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - change_request_vars.yml
    - vmware_vars.yml
    - vsp_direct_variables.yml

  tasks:
  - name: Create a change request
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "Requested for creation of '{{ datastore_name }}' backed by ldev '{{ hostgroup_ldevs_1 }}' on '{{ inventory_hostname }}'"
    register: new_incident
  - debug:
      var: new_incident.record