- name: VMWare rescan Storage
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  vars_files:
    - vmware_vars.yaml

  tasks:
  - name: Rescan HBA's for a given ESXi host and refresh storage system objects
    community.vmware.vmware_host_scanhba:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      refresh_storage: true
