---
- name: ServiceNow Incident Automation
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000 # Custom port
  rules:
    - name: New Incident
      condition:
        all:
          - event.category == "hardware"
          - event.state == "6"
      action:
        run_job_template:
          name: "rescan_storage.yaml"
          organization: "Hitachi Ltd"
