####################################################################
# Example : LDEV  Playbook
####################################################################
- name: Logical Device Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ansible_vault_storage.yaml
    - vsp_direct_variables.yaml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
  - name: Present ldevs to hostgroup CL2A
    hitachivantara.vspone_block.vsp.hv_hg:
      connection_info: "{{ connection_info }}"
      storage_system_info:
        serial: "{{ storage_serial }}"
      state: "present"
      spec:
        state: "present"
        name: "{{hostgroup_name_2}}"
        port: "{{hostgroup_port_2}}"
        host_mode_options: "{{ hostgroup_host_mode_options_2 }}"
        ldevs: "{{ ldev_id }}"
    register: host_group_create

  - debug:
      var: host_group_create
