- name: VMWare rescan Storage
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  vars_files:
    - vmware_vars.yaml

  tasks:
  - name: Mount VMFS datastores to ESXi
    community.vmware.vmware_host_datastore:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datastore_name: '{{ datastore_name }}'
      datastore_type: '{{ datastore_type }}'
      vmfs_device_name: '{{ vmfs_device_name }}'
      vmfs_version: 6
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'

