####################################################################
# Variables for hostgroup playbook
####################################################################
# Task 1 : Create hostgroup for CL1-A
####################################################################
hostgroup_name_1 : DC3-ESXi-224
hostgroup_port_1 : CL1-A
hostgroup_host_mode_1 : VMWARE_EXTENSION
hostgroup_host_mode_options_1 : [ 54, 63 ]
hostgroup_ldevs_1 : [ 936 ]
hostgroup_wwns_1 :
  - 100000109B33A6DB
####################################################################
# Task 2 : Create hostgroup for CL1-A
####################################################################
hostgroup_name_2 : DC3-ESXi-224
hostgroup_port_2 : CL2-A
hostgroup_host_mode_2 : VMWARE_EXTENSION
hostgroup_host_mode_options_2 : [ 54, 63 ]
hostgroup_ldevs_2 : [ 936 ]
hostgroup_wwns_2 :
  - 100000109B33A6DC
